### PR TITLE
Address vulnerabilities

### PR DESCRIPTION
**Pull request by jssuttles**
Updated all the packages.
Replaced watch (which is not maintained https://github.com/mikeal/watch/issues/149) with chokidar

### CODE REVIEW

**Comment by hitgeek** [comment]
do the tests pass for you locally? I am unable to get the tests to pass. 

Note: `watch` dependency is removed in v4, you can get that from npm via simple-hl7@next .... I haven't had much time to test so that version is still considered beta. there are also going to be some breaking changes in v4 to better align with the hl7 spec, but I haven't got around to those yet.

**Comment by hitgeek** [comment]
@jssuttles would this work for you. https://github.com/hitgeek/simple-hl7/pull/71

**Comment by Djeisen642** [comment]
The tests worked for me. I'll have to get back around to looking at it maybe later today. (What do you see when they fail? I'm not too familiar with what failure looks like in this set of tests.)

If you're refactoring the system, then I don't mind waiting for the package to get stable. I was just trying to help get this vulnerable package out of this repo.

I'm not personally a fan of copying code out of a package, because you lose all the tests that might have been in place with that package.

**Comment by jssuttles** [comment]
I see. Now I see the tests not passing. I'll see what I can do.

**Comment by jssuttles** [comment]
Perhaps the file was not fully written, and therefore there were inconsistent test results?

**Pull request closed without merging**
