### PR TITLE
make tcp client reusable

### PR DESCRIPTION
**Pull request by jssuttles**
I was having trouble sending multiple hl7 messages to dcm4che hl7rcv (https://github.com/dcm4che/dcm4che/blob/master/dcm4che-tool/dcm4che-tool-hl7rcv/README.md)

So, I researched a bit and came across this: https://stackoverflow.com/a/4307337/4905960

Made the tcp client reusable and it worked.

### CODE REVIEW

**Comment by hitgeek** [comment]
thanks for the PR!

does this work? https://github.com/hitgeek/simple-hl7/commit/101c4d11b266fb5523715016f6d535820ed9fc71

I added a `keepalive` option on `createTcpClient`. You can also specificy a global callback for acks in this scenario.

the only thing to be careful of is sending multiple messages all at once. The client isn't smart enough to buffer or queue them, so it will throw an error if you try to send a message before it got the response from the last one. 

this is on npm as version 2.0.1.

```
var client = hl7.Server.createTcpClient({
  host: 'localhost',
  port: 7777,
  keepalive: true,
  callback: function(err, ack) {
    if (err) {
      console.log("*******ERROR********");
      console.log(err.message);
    } else {
      console.log(ack.log());
    }
  }
});

console.log('************sending 1 message****************');
client.send(msg);

//This will probably throw an error
client.send(msg);

//these will not
setTimeout(function() {
  console.log('************sending 2 message****************');
  client.send(msg);
}, 1000);

setTimeout(function() {
  console.log('************sending 3 message****************');
  client.send(msg);
}, 2000);


```

**Comment by jssuttles** [comment]
Yeah, that works. 
Thanks for looking into it and building a better solution.

**Comment by jssuttles** [comment]
Maybe something like a promise queue might help: https://www.npmjs.com/package/promise-queue

**Comment by hitgeek** [comment]
i don't see that being a feature I would implement, but I'd be open to a PR.

**Pull request closed without merging**
